<?php
/**
 * =====================================================================
 * PAAR — admin/notifications.php
 * ---------------------------------------------------------------------
 * Broadcast in-app notifications to all active patients OR to a single
 * patient, and view a log of recent notifications generated by the system.
 * =====================================================================
 */

require_once __DIR__ . '/../includes/auth_check.php';
require_role('admin');

$pdo = db();

/* ---- POST: broadcast --------------------------------------------- */
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();

    $audience  = $_POST['audience']  ?? 'all';
    $patientId = (int) ($_POST['patient_id'] ?? 0);
    $message   = trim($_POST['message'] ?? '');

    if ($message === '' || mb_strlen($message) > 1000) {
        flash('danger', 'Message must be between 1 and 1000 characters.');
        redirect(base_url('admin/notifications.php'));
    }

    $stmt = $pdo->prepare('INSERT INTO notifications (user_id, message) VALUES (?, ?)');
    $count = 0;

    if ($audience === 'one' && $patientId > 0) {
        $u = $pdo->prepare(
            'SELECT u.user_id FROM users u
               JOIN patients p ON p.user_id = u.user_id
              WHERE p.patient_id = ? AND u.status="active"'
        );
        $u->execute([$patientId]);
        if ($uid = $u->fetchColumn()) {
            $stmt->execute([$uid, $message]);
            $count = 1;
        }
    } else {
        // Broadcast to all active patients.
        $rs = $pdo->query(
            "SELECT u.user_id FROM users u
              WHERE u.role='patient' AND u.status='active'"
        );
        foreach ($rs as $row) {
            $stmt->execute([$row['user_id'], $message]);
            $count++;
        }
    }

    flash('success', 'Notification sent to ' . $count . ' recipient' . ($count===1?'':'s') . '.');
    redirect(base_url('admin/notifications.php'));
}

/* ---- Data --------------------------------------------------------- */
$patients = $pdo->query("
    SELECT p.patient_id, u.name FROM patients p JOIN users u ON u.user_id = p.user_id
     WHERE u.status='active' ORDER BY u.name
")->fetchAll();

$recent = $pdo->query("
    SELECT n.*, u.name AS recipient_name, u.role
      FROM notifications n
      JOIN users u ON u.user_id = n.user_id
     ORDER BY n.created_at DESC
     LIMIT 100
")->fetchAll();

$page_title   = 'Notifications';
$page_section = 'notifications';
include __DIR__ . '/../includes/header.php';
include __DIR__ . '/../includes/sidebar_admin.php';
?>

<div class="page-head">
    <div>
        <h1>Notifications</h1>
        <div class="subtitle">Send in-app messages to patients.</div>
    </div>
</div>

<div class="grid-2">
    <div class="card">
        <div class="card__header"><h3 class="card__title">Send a message</h3></div>
        <form method="post" novalidate>
            <div class="form-group">
                <label>Audience</label>
                <div class="btn-row">
                    <label class="label-inline">
                        <input type="radio" name="audience" value="all" checked> All active patients
                    </label>
                    <label class="label-inline">
                        <input type="radio" name="audience" value="one"> Single patient
                    </label>
                </div>
            </div>

            <div class="form-group">
                <label for="patient_id">Patient (only used if "Single patient")</label>
                <select id="patient_id" name="patient_id" class="input">
                    <option value="0">—</option>
                    <?php foreach ($patients as $p): ?>
                        <option value="<?= (int)$p['patient_id'] ?>"><?= e($p['name']) ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group">
                <label for="message">Message *</label>
                <textarea id="message" name="message" class="input" required maxlength="1000"
                          placeholder="Type your announcement..."></textarea>
                <div class="field-help">Up to 1000 characters.</div>
            </div>

            <?= csrf_field() ?>
            <button type="submit" class="btn btn--accent">Send</button>
        </form>
    </div>

    <div class="card">
        <div class="card__header">
            <h3 class="card__title">Recent notifications</h3>
            <span class="text-muted"><?= count($recent) ?></span>
        </div>
        <?php if (!$recent): ?>
            <div class="text-muted">Nothing sent yet.</div>
        <?php else: ?>
            <ul class="notif-list">
                <?php foreach ($recent as $n): ?>
                    <li class="<?= $n['is_read'] ? '' : 'unread' ?>">
                        <div class="flex-1">
                            <div><?= e($n['message']) ?></div>
                            <div class="when text-muted text-12 mt-2">
                                To <b><?= e($n['recipient_name']) ?></b>
                                (<?= e($n['role']) ?>)
                                · <?= e(date('M j, Y · H:i', strtotime($n['created_at']))) ?>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>

<?php include __DIR__ . '/../includes/footer.php'; ?>
